# Generated by Django 4.2.29 on 2026-03-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short, simple, easy-to-remember title', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('sql', models.TextField()),
            ],
            options={
                'verbose_name': 'flat query',
                'verbose_name_plural': 'flat queries',
                'permissions': (('can_run_query', 'Can run query'),),
            },
        ),
    ]
